# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSosa():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sosa(self):
    self.driver.get("https://ura.news/news/1052773324")
    self.driver.set_window_size(1845, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-group:nth-child(3) > .btn-comments-expand").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comment-form:nth-child(5) .comment-form-bottom-text > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty").send_keys("AaaAaA")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-valid-maxlength").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-valid-maxlength").send_keys("name")
    self.driver.find_element(By.CSS_SELECTOR, ".vc-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#comment_form_ > .ng-valid").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".comment-form-bottom:nth-child(3) > .comment-form-send > .btn").click()
  